### ISSUE TITLE
Training with 3 channels images

### ISSUE THREAD

**Issue by procton** [CosmiQ/CosmiQ_SN6_Baseline#3]
The current solution forces the use of 4 channels images. Trying to  use 3 channel images I have the following error even having specified in the YAML configuration image type = 24 bit and channels = 3
```
Traceback (most recent call last):
  File "./baseline.py", line 883, in <module>
    train(args)
  File "./baseline.py", line 599, in train
    trainer.train()
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/solaris/nets/train.py", line 139, in train
    output = self.model(data)
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/model.py", line 95, in forward
    conv1 = self.relu(self.conv1(x))
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 4 3 3, expected input[8, 3, 512, 512] to have 4 channels, but got 3 channels instead
```

**Comment by procton** [comment]
I got it ... the number of channel can be set in `model.py` in `def make_layers(cfg, batch_norm=False, bands=3) `

**Comment by procton** [comment]
closing the issue
